sonar.projectKey=siimpli-graph-it-core
sonar.projectName=siimpli-graph-it-core
sonar.projectVersion=0.3.63

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

# Enable this after generating JS/TS lcov coverage output.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
